Update the schedule for the coach meetings.
WISVCH/nwerc-2022 pull request #39
Opened 2022-11-14 15:42 UTC by verwoerd

2022-11-15 07:49 UTC, robertdijk requested changes
I'm not sure if we'll use those entrances, or the entrances one floor down.

2022-11-15 07:49 UTC, robertdijk commented on content/schedule/coach_meeting_bapc.md
> +The entrance of the hall D is on the top floor, and indicated on the signs.
```suggestion
The entrance of the hall D is indicated on the signs.
```

2022-11-15 07:49 UTC, robertdijk commented on content/schedule/coach_meeting_gcpc.md
> +The entrance of the hall D is on the top floor, and indicated on the signs.
```suggestion
The entrance of the hall D is indicated on the signs.
```

2022-11-15 07:49 UTC, robertdijk commented on content/schedule/coach_meeting_ncpc.md
> +The entrance of the hall C is on the top floor, and indicated on the signs.
```suggestion
The entrance of the hall C is indicated on the signs.
```

2022-11-15 07:49 UTC, robertdijk commented on content/schedule/coach_meeting_ukiepc.md
> +The entrance of the hall D is on the top floor, and indicated on the signs.
```suggestion
The entrance of the hall D is indicated on the signs.
```

2022-11-15 11:07 UTC, robertdijk approved these changes

2022-11-16 13:48 UTC, mpsijm approved these changes
Fixed a few small things, you can merge if you agree :smile:

2022-11-16 16:23 UTC, merged