Activity page updated with info that is also in the form.
WISVCH/nwerc-2022 pull request #42
Opened 2022-11-21 13:32 UTC by raoulesd

This PR can be merged once the last information email has been sent out. In the meantime, people can give feedback on content/formatting.

I also added a news update about the activity page update so people can more easily find the page.

2022-11-21 16:24 UTC, verwoerd requested changes

2022-11-21 16:24 UTC, verwoerd commented on content/news/activities-updated.md
> +ß
```suggestion

```

2022-11-21 19:19 UTC, mpsijm approved these changes
LGTM (besides Verwoerd's fix) :smile:

2022-11-22 18:47 UTC, verwoerd approved these changes

2022-11-22 18:49 UTC, merged