Create spectator-contest.md
WISVCH/nwerc-2022 pull request #45
Opened 2022-11-24 15:22 UTC by robertdijk

2022-11-24 20:05 UTC, mpsijm requested changes

2022-11-24 20:05 UTC, mpsijm commented on content/news/spectator-contest.md
> +title: "Livestream URLs"
```suggestion
title: "Spectator contest"
```

2022-11-24 20:05 UTC, mpsijm commented on content/news/spectator-contest.md
> +There will be a spectator contest hosted on [spectator.nwerc.eu](http://spectator.nwerc.eu).
```suggestion
There will be a spectator contest hosted on [spectator.nwerc.eu](https://spectator.nwerc.eu).
```

2022-11-24 20:05 UTC, mpsijm commented on content/news/spectator-contest.md
> +The contest will start at 10:30 on Sunday (November 27 2022). This is half an our later then the real contest.
```suggestion
The contest will start at 10:30 CET on Sunday (November 27th, 2022). This is half an our later than the start of the real contest.
```

2022-11-25 07:36 UTC, verwoerd approved these changes

2022-11-25 08:33 UTC, mpsijm approved these changes
Looking good! Any reason why this PR is still marked as draft? Else it can be merged :slightly_smiling_face:

2022-11-25 10:01 UTC, robertdijk commented
Yea I'm not yet sure if the config in domjudge is fully correct and ready. @mpsijm could you check it?

2022-11-25 10:04 UTC, merged